# Form implementation generated from reading ui file 'd:\mypro\yt blocker\yt_blocker.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
import webbrowser
import sys
import sqlite3
import shutil
#===================defs===================
def basedir1():
        if getattr(sys, 'frozen', False):
                return os.path.dirname(sys.executable)
        elif __file__:
                return os.path.dirname(__file__)
basedir = os.path.dirname(__file__)
#Thanks gezine for YT Update Blocker
def appinfoeditor(input_path:str,output_path):
    if "appinfo.db" not in input_path:
        print("Error: appinfo.db file not found!")
    else:
        print("Creating backup...")
        shutil.copy(input_path, f'{output_path}\\appinfo.org.db')
        print(f"Backup created: {output_path}\\appinfo.org.db")

        conn = sqlite3.connect(input_path)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT key, val 
            FROM tbl_appinfo 
            WHERE titleId = 'PPSA01650' 
            AND key IN ('CONTENT_VERSION', 'VERSION_FILE_URI')
""")

        results = cursor.fetchall()

        if len(results) != 2:
            print(f"Error: Expected 2 keys but found {len(results)}")
            print("Required keys: CONTENT_VERSION, VERSION_FILE_URI")
            print(f"Found keys: {[row[0] for row in results]}")
            conn.close()
            exit(1)

        print("All required keys found. Proceeding with updates...\n")

        cursor.execute("""
            UPDATE tbl_appinfo 
            SET val = '99.999.999'
            WHERE titleId = 'PPSA01650' 
            AND key = 'CONTENT_VERSION'
""")
        print(f"Updated CONTENT_VERSION (rows affected: {cursor.rowcount})")

        cursor.execute("""
            UPDATE tbl_appinfo 
            SET val = 'http://127.0.0.2'
            WHERE titleId = 'PPSA01650'
            AND key = 'VERSION_FILE_URI'
""")
        print(f"Updated VERSION_FILE_URI (rows affected: {cursor.rowcount})")

        conn.commit()

        print("\nVerifying changes...")
        cursor.execute("""
            SELECT key, val 
            FROM tbl_appinfo 
            WHERE titleId = 'PPSA01650' 
            AND key IN ('CONTENT_VERSION', 'VERSION_FILE_URI')
""")

        for row in cursor.fetchall():
            print(f"  {row[0]}: {row[1]}")

        conn.close()

        print(f"\nChanges saved to {input_path}")
        print(f"Original backed up to {output_path}\\appinfo.org.db'")

#===================classes===================
class EmittingStream:
    def __init__(self, write_func):
        self.write_func = write_func

    def write(self, text):
        if text.strip():  # فقط وقتی متن خالی نیست
            self.write_func(text)

    def flush(self):
        pass
#===================UI===================
class Ui_YT_update_blocker(object):
    def setupUi(self, YT_update_blocker):
        YT_update_blocker.setObjectName("YT_update_blocker")
        YT_update_blocker.resize(394, 242)
        YT_update_blocker.setMinimumSize(QtCore.QSize(394, 242))
        YT_update_blocker.setMaximumSize(QtCore.QSize(394, 242))
#===========================================centralwidget
        self.centralwidget = QtWidgets.QWidget(parent=YT_update_blocker)
        self.centralwidget.setObjectName("centralwidget")
#===========================================le_select_db_path
        self.le_select_db_path = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_select_db_path.setGeometry(QtCore.QRect(20, 10, 271, 20))
        self.le_select_db_path.setObjectName("le_select_db_path")
        self.le_select_db_path.setPlaceholderText("appinfo.db Path")
#===========================================le_select_backup_path
        self.le_select_backup_path = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_select_backup_path.setGeometry(QtCore.QRect(20, 40, 271, 20))
        self.le_select_backup_path.setObjectName("le_select_backup_path")
        self.le_select_backup_path.setPlaceholderText("Backup Path")
#===========================================btn_select_db_path
        self.btn_select_db_path = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_select_db_path.setGeometry(QtCore.QRect(300, 10, 75, 21))
        self.btn_select_db_path.setObjectName("btn_select_db_path")
        self.btn_select_db_path.clicked.connect(lambda:self.select_path(type1 = "file",le_adress = self.le_select_db_path))
#===========================================btn_select_backup_path
        self.btn_select_backup_path = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_select_backup_path.setGeometry(QtCore.QRect(300, 40, 75, 21))
        self.btn_select_backup_path.setObjectName("btn_select_backup_path")
        self.btn_select_backup_path.clicked.connect(lambda:self.select_path(type1 = "folder",le_adress = self.le_select_backup_path))
#===========================================btn_start_process
        self.btn_start_process = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_start_process.setGeometry(QtCore.QRect(20, 70, 351, 41))
        self.btn_start_process.setObjectName("btn_start_process")
        self.btn_start_process.clicked.connect(lambda: self.start_process())
#===========================================lbl_log
        self.lbl_log = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_log.setGeometry(QtCore.QRect(20, 120, 351, 61))
        self.lbl_log.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_log.setText("")
        self.lbl_log.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_log.setObjectName("lbl_log")
        sys.stdout = EmittingStream(self.append_log)
        self.scroll_area = QtWidgets.QScrollArea(self.centralwidget)
        self.scroll_area.setGeometry(QtCore.QRect(20, 120, 351, 61))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setWidget(self.lbl_log)
#===========================================menubar
        YT_update_blocker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=YT_update_blocker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 394, 21))
        self.menubar.setObjectName("menubar")
#===========================================================================aboutMnu
        self.aboutMnu = QtWidgets.QMenu(self.menubar)
        self.aboutMnu.setObjectName("aboutMnu")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        YT_update_blocker.setMenuBar(self.menubar)
#===========================================================================aTeleChnl
        self.aTeleChnl = QtGui.QAction(YT_update_blocker)
        self.aTeleChnl.setObjectName("aTeleChnl")
        iconTel=QtGui.QIcon()
        iconTel.addPixmap(QtGui.QPixmap(os.path.join(basedir,'app_pics\\Telegramlogo.png')),QtGui.QIcon.Mode.Normal)
        self.aTeleChnl.setIcon(iconTel)
#===========================================================================aYTChnl
        self.aYTChnl = QtGui.QAction(YT_update_blocker)
        self.aYTChnl.setObjectName("aYTChnl")
        iconYT=QtGui.QIcon()
        iconYT.addPixmap(QtGui.QPixmap(os.path.join(basedir,'app_pics\\YouTubelogo.png')),QtGui.QIcon.Mode.Normal)
        self.aYTChnl.setIcon(iconYT)
#===========================================================================aGithubPage
        self.aGithubPage = QtGui.QAction(YT_update_blocker)
        self.aGithubPage.setObjectName("aGithubPage")
        iconGit=QtGui.QIcon()
        iconGit.addPixmap(QtGui.QPixmap(os.path.join(basedir,'app_pics\\GitHubLogo.png')),QtGui.QIcon.Mode.Normal)
        self.aGithubPage.setIcon(iconGit)
#===========================================================================aboutMnu
        self.aboutMnu.addAction(self.aTeleChnl)
        self.aboutMnu.addAction(self.aYTChnl)
        self.aboutMnu.addAction(self.aGithubPage)
#===========================================statusbar
        YT_update_blocker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=YT_update_blocker)
        self.statusbar.setObjectName("statusbar")
#===========================================
        YT_update_blocker.setStatusBar(self.statusbar)
        self.menubar.addAction(self.aboutMnu.menuAction())
        self.aboutMnu.triggered[QtGui.QAction].connect(self.dmenuAbout)
        self.retranslateUi(YT_update_blocker)
        QtCore.QMetaObject.connectSlotsByName(YT_update_blocker)

    def retranslateUi(self, YT_update_blocker):
        _translate = QtCore.QCoreApplication.translate
        YT_update_blocker.setWindowTitle(_translate("YT_update_blocker", "YT Update Blocker"))
        self.btn_select_db_path.setText(_translate("YT_update_blocker", "Path..."))
        self.btn_select_backup_path.setText(_translate("YT_update_blocker", "Path..."))
        self.btn_start_process.setText(_translate("YT_update_blocker", "Start Process"))
        self.aboutMnu.setTitle(_translate("META_SITE", "About US"))
        self.aTeleChnl.setText(_translate("META_SITE", "Telegram Channel"))
        self.aYTChnl.setText(_translate("META_SITE", "Youtube Channel"))
        self.aGithubPage.setText(_translate("META_SITE", "Github Page"))
#=========================================== ui defs
    def dmenuAbout(self,q):
        if q.objectName()=="aTeleChnl":
                webbrowser.open('https://t.me/sinajet')
        elif q.objectName()=="aYTChnl":
                webbrowser.open('https://www.youtube.com/c/SinaJet')
        elif q.objectName()=="aGithubPage":
                webbrowser.open('https://github.com/sinajet')

    def append_log(self, text):
        current = self.lbl_log.text()
        if current != '':
            self.lbl_log.setText(current + "\n" + text)
        else:
            self.lbl_log.setText(text)


    def select_path(self,type1:str,le_adress:None):
        try:
            base_path = le_adress.text()
            if base_path == "":
                folder_path = basedir1()
            else:
                folder_path = base_path

            if type1 == "file":
                if os.path.exists(folder_path):
                        fname = QtWidgets.QFileDialog.getOpenFileName(None, "select db File", folder_path, "Database file (*.db)")
                        le_adress.setText(fname[0])
                else:
                        fname = QtWidgets.QFileDialog.getOpenFileName(None, "select db File", 'Desktop', "Database file (*.db)")
                        le_adress.setText(fname[0])
            elif type1 == "folder":
                if os.path.exists(folder_path):
                        fpath = QtWidgets.QFileDialog.getExistingDirectory(None,'Select output Folder',folder_path)
                        le_adress.setText(fpath)
                else:
                        fpath = QtWidgets.QFileDialog.getExistingDirectory(None,'Select output Folder','Desktop',)
                        le_adress.setText(fpath)
        except:
            pass

    def start_process(self):
        db_path = self.le_select_db_path.text()
        backup_path = self.le_select_backup_path.text()
        if db_path == "" and backup_path == "":
            print("Error: Paths are empty!")
        else:
            if not os.path.exists(db_path):
                print("Error: db path is incorect!")
            else:
                if not os.path.exists(backup_path):
                    print("Error: backup path is incorect!")
                else:
                    appinfoeditor(input_path=db_path,output_path=backup_path)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    YT_update_blocker = QtWidgets.QMainWindow()
    app.setWindowIcon(QtGui.QIcon(os.path.join(basedir,'app_pics/','icon.ico')))
    ui = Ui_YT_update_blocker()
    ui.setupUi(YT_update_blocker)
    YT_update_blocker.show()
    sys.exit(app.exec())
