# Form implementation generated from reading ui file 'd:\mypro\Nintenland_content\Project_server\Link_maker.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#============================================Libraries=======================================
from PyQt6 import QtCore, QtGui, QtWidgets
import os,sys
from slugify import slugify
from NXGameInfo import nx_game_info
import pyperclip as pc
import re
import subprocess
#===========================================Public Var=======================================
def basedir1():
        if getattr(sys, 'frozen', False):
                return os.path.dirname(sys.executable)
        elif __file__:
                return os.path.dirname(__file__)
dict_en_server_link={}
server_en_index=0
game_path = r'D:\ninntendo'
nx_info_path = basedir1() + "/NX_game_info/nxgameinfo_cli.exe"
dict_type = {
                'Base' :'base',
                'Update' :'update',
                'DLC' : 'dlc'
        }

dict_dlc = {}
list_dlc = []
#==========================================Public defs=======================================
def notify(txt = ''):
        ui.lbl_notify.setText(txt)
        QtCore.QTimer.singleShot(4000,lambda:ui.lbl_notify.setText(''))

def dotify(text):
        # حذف تمام کاراکترهای غیر الفبایی به جز فاصله‌ها
        text = text.replace('.', ' ')
        text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
        slug = text.replace(' ', '.')
        return slug

def true_path(path = ''):
        return os.path.join(basedir1()+path.replace('/','\\'))

def copy(text = '',note = ''):
        pc.copy(text)
        notify(f"{note} با موفقیت کپی شد.")

def convert_bytes(size):
        for x in ['bytes','KB','MB','GB','TB']:
                if size < 1024.0:
                        return'%3.1f%s'%(size,x)
                size/=1024.0
        return size

def Jamelist(list):
        text=""
        Lenlist=len(list)
        for i in range(Lenlist):
                QtWidgets.QApplication.processEvents()
                if i!=Lenlist-1:
                        text=text+list[i]+"\n"
                else:
                        text=text+list[i]
        return text

def rename_file(file_path, new_name):
        directory, original_file_name = os.path.split(file_path)
        file_extension = os.path.splitext(original_file_name)[1]
        new_file_name = new_name + file_extension
        new_file_path = os.path.join(directory, new_file_name)
        os.rename(file_path, new_file_path)
        return new_file_path

def txt_reader(path = ''):
        text_file = open(path,'r',encoding="utf8")
        text = text_file.read()
        text_file.close()
        return text
list_server = txt_reader(true_path("/setting/server_list.in")).splitlines()
list_settings = txt_reader(true_path("/setting/settings.in")).splitlines()

for serv in range(len(list_server)): # Important to make dict_en_server_link first,its usefull on for loops changing
        dict_en_server_link.update({str(serv):['','','','','','','','','','','','']})

def txt_saver(txt,path = ''):
        output_file = open(path , 'w', encoding='utf-8')
        output_file.write(txt)
        output_file.close()

def find_nsp_and_xci_files(directory_path):
        try:
                global dict_dlc,list_dlc
                dict_dlc.clear()
                list_dlc.clear()
                for root, dirs, files in os.walk(directory_path):
                        QtWidgets.QApplication.processEvents()
                        for file in files:
                                if file.endswith('.nsp') or file.endswith('.xci'):
                                        dlc_path =os.path.join(root, file)
                                        dict_dlc_info = nx_game_info(exe_path = nx_info_path, game_path = dlc_path)[0]
                                        dict_dlc[file[:-4]] = [dlc_path, dict_dlc_info['Title ID'], "v"+dict_dlc_info['Version']]
                ui.le_dlc_title_id.setText(dict_dlc_info['Title ID'])
                ui.le_dlc_version.setText(dict_dlc_info['Version'])
                list_dlc = list(dict_dlc.keys())
                ui.txt_dlc_names.setPlainText(Jamelist(list_dlc))
        except:
                pass

def find_rar_files(directory_path):
        try:
                rar_files = []
                # لیست فایل‌ها در مسیر داده شده
                for file in os.listdir(directory_path):
                        QtWidgets.QApplication.processEvents()
                        # بررسی اینکه آیتم مورد نظر فایل با پسوند .rar باشد
                        if file.endswith('.rar'):
                                # ساختار مسیر فایل
                                rar_path = os.path.basename(directory_path) + '/' + os.path.basename(file)
                                rar_files.append([rar_path, os.path.basename(directory_path)])
                return rar_files
        except Exception as e:
                print(f"An error occurred: {e}")
                return []


def folder_size(path='.'):
        QtWidgets.QApplication.processEvents()
        folder_size_cmd = "powershell (gci -Path '"+str(path)+"' -Recurse| Measure-Object -Property Length -s).sum"
        folder_size_output=subprocess.check_output(folder_size_cmd)
        return convert_bytes(int(folder_size_output.decode('utf-8')))

def txt_links_en_maker(txt_links_base = str):
        list_links=txt_links_base.splitlines() 
        len_list_links = len(list_links)
        if len_list_links == 2:
                return list_links
        else:
                return [0,'']

#===============================================UI===========================================
class Ui_link_maker(object):
    def setupUi(self, link_maker):
        link_maker.setObjectName("link_maker")
        link_maker.resize(718, 545)
        link_maker.setMinimumSize(QtCore.QSize(718, 545))
        link_maker.setMaximumSize(QtCore.QSize(718, 545))
        self.centralwidget = QtWidgets.QWidget(parent=link_maker)
        self.centralwidget.setObjectName("centralwidget")
#==========================================================================================all_tabs
        self.all_tabs = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.all_tabs.setGeometry(QtCore.QRect(10, 0, 701, 451))
        self.all_tabs.setObjectName("all_tabs")
#==========================================================================================tan_rename
        self.tan_rename = QtWidgets.QWidget()
        self.tan_rename.setObjectName("tan_rename")
#==========================================================================================gb_base_re
        self.gb_base_re = QtWidgets.QGroupBox(parent=self.tan_rename)
        self.gb_base_re.setGeometry(QtCore.QRect(0, 10, 691, 80))
        self.gb_base_re.setObjectName("gb_base_re")
#==========================================================================================btn_base_rename_file
        self.btn_base_rename_file = QtWidgets.QPushButton(parent=self.gb_base_re)
        self.btn_base_rename_file.setGeometry(QtCore.QRect(569, 46, 75, 23))
        self.btn_base_rename_file.setObjectName("btn_base_rename_file")
        self.btn_base_rename_file.clicked.connect(lambda:self.rename_game_file('base'))
#==========================================================================================le_base_version
        self.le_base_version = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_version.setGeometry(QtCore.QRect(379, 16, 61, 20))
        self.le_base_version.setObjectName("le_base_version")
#==========================================================================================lbl_base_format
        self.lbl_base_format = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_format_maker(self.lbl_base_format,"lbl_base_format",649, 20, 31, 16)
        self.lbl_base_format.setText('<a href="#">.nsp</a>')
        self.lbl_base_format.linkActivated.connect(lambda:copy(text = self.le_base_name.text()+'-'+self.le_base_title_id.text(), note = "اسم فولدر"))
#==========================================================================================lbl_line_1-6
        self.lbl_line_1 = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_line_maker(self.lbl_line_1,"lbl_line_1",40, 20, 16, 16)
        self.lbl_line_2 = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_line_maker(self.lbl_line_2,"lbl_line_2",250, 20, 16, 16)
        self.lbl_line_3 = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_line_maker(self.lbl_line_3,"lbl_line_3",371, 20, 16, 16)
        self.lbl_line_4 = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_line_maker(self.lbl_line_4,"lbl_line_4",440, 20, 16, 16)
        self.lbl_line_5 = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_line_maker(self.lbl_line_5,"lbl_line_5",509, 20, 16, 16)
        self.lbl_line_6 = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_line_maker(self.lbl_line_6,"lbl_line_6",579, 20, 16, 16)
#==========================================================================================lbl_base_file_path
        self.lbl_base_file_path = QtWidgets.QLabel(parent=self.gb_base_re)
        self.lbl_base_file_path.setGeometry(QtCore.QRect(110, 46, 451, 20))
        self.lbl_base_file_path.setObjectName("lbl_base_file_path")
#==========================================================================================le_base_dv
        self.le_base_dv = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_dv.setGeometry(QtCore.QRect(518, 16, 61, 20))
        self.le_base_dv.setObjectName("le_base_dv")
#==========================================================================================btn_base_select_file
        self.btn_base_select_file = QtWidgets.QPushButton(parent=self.gb_base_re)
        self.btn_base_select_file.setGeometry(QtCore.QRect(29, 46, 75, 23))
        self.btn_base_select_file.setObjectName("btn_base_select_file")
        self.btn_base_select_file.clicked.connect(lambda: self.choose_game_file('base'))
#==========================================================================================le_base_site
        self.le_base_site = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_site.setGeometry(QtCore.QRect(589, 16, 61, 20))
        self.le_base_site.setObjectName("le_base_site")
#==========================================================================================le_base_sdkv
        self.le_base_sdkv = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_sdkv.setGeometry(QtCore.QRect(449, 16, 61, 20))
        self.le_base_sdkv.setObjectName("le_base_sdkv")
#==========================================================================================le_base_title_id
        self.le_base_title_id = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_title_id.setGeometry(QtCore.QRect(259, 16, 111, 20))
        self.le_base_title_id.setObjectName("le_base_title_id")
#==========================================================================================le_base_name
        self.le_base_name = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_name.setGeometry(QtCore.QRect(49, 16, 201, 20))
        self.le_base_name.setObjectName("le_base_name")
#==========================================================================================le_base_format
        self.le_base_format = QtWidgets.QLineEdit(parent=self.gb_base_re)
        self.le_base_format.setGeometry(QtCore.QRect(9, 16, 31, 20))
        self.le_base_format.setObjectName("le_base_format")
#==========================================================================================gb_update_re
        self.gb_update_re = QtWidgets.QGroupBox(parent=self.tan_rename)
        self.gb_update_re.setGeometry(QtCore.QRect(0, 120, 691, 80))
        self.gb_update_re.setObjectName("gb_update_re")
#==========================================================================================btn_update_rename_file
        self.btn_update_rename_file = QtWidgets.QPushButton(parent=self.gb_update_re)
        self.btn_update_rename_file.setGeometry(QtCore.QRect(569, 46, 75, 23))
        self.btn_update_rename_file.setObjectName("btn_update_rename_file")
        self.btn_update_rename_file.clicked.connect(lambda: self.rename_game_file('update'))
#==========================================================================================le_update_version
        self.le_update_version = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_version.setGeometry(QtCore.QRect(379, 16, 61, 20))
        self.le_update_version.setObjectName("le_update_version")
#==========================================================================================lbl_update_format
        self.lbl_update_format = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_format_maker(self.lbl_update_format,"lbl_update_format",649, 20, 31, 16)
#==========================================================================================lbl_line_7-12
        self.lbl_line_7 = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_line_maker(self.lbl_line_7,"lbl_line_7",40, 20, 16, 16)
        self.lbl_line_8 = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_line_maker(self.lbl_line_8,"lbl_line_8",250, 20, 16, 16)
        self.lbl_line_9 = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_line_maker(self.lbl_line_9,"lbl_line_9",371, 20, 16, 16)
        self.lbl_line_10 = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_line_maker(self.lbl_line_10,"lbl_line_10",440, 20, 16, 16)
        self.lbl_line_11 = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_line_maker(self.lbl_line_11,"lbl_line_11",509, 20, 16, 16)
        self.lbl_line_12 = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_line_maker(self.lbl_line_12,"lbl_line_12",579, 20, 16, 16)
#==========================================================================================lbl_update_file_path
        self.lbl_update_file_path = QtWidgets.QLabel(parent=self.gb_update_re)
        self.lbl_update_file_path.setGeometry(QtCore.QRect(110, 46, 451, 20))
        self.lbl_update_file_path.setObjectName("lbl_update_file_path")
#==========================================================================================le_update_dv
        self.le_update_dv = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_dv.setGeometry(QtCore.QRect(518, 16, 61, 20))
        self.le_update_dv.setObjectName("le_update_dv")
#==========================================================================================btn_update_select_file
        self.btn_update_select_file = QtWidgets.QPushButton(parent=self.gb_update_re)
        self.btn_update_select_file.setGeometry(QtCore.QRect(29, 46, 75, 23))
        self.btn_update_select_file.setObjectName("btn_update_select_file")
        self.btn_update_select_file.clicked.connect(lambda: self.choose_game_file('update'))
#==========================================================================================le_update_site
        self.le_update_site = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_site.setGeometry(QtCore.QRect(589, 16, 61, 20))
        self.le_update_site.setObjectName("le_update_site")
#==========================================================================================le_update_sdkv
        self.le_update_sdkv = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_sdkv.setGeometry(QtCore.QRect(449, 16, 61, 20))
        self.le_update_sdkv.setObjectName("le_update_sdkv")
#==========================================================================================le_update_title_id
        self.le_update_title_id = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_title_id.setGeometry(QtCore.QRect(259, 16, 111, 20))
        self.le_update_title_id.setObjectName("le_update_title_id")
#==========================================================================================le_update_name
        self.le_update_name = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_name.setGeometry(QtCore.QRect(49, 16, 201, 20))
        self.le_update_name.setObjectName("le_update_name")
#==========================================================================================le_update_format
        self.le_update_format = QtWidgets.QLineEdit(parent=self.gb_update_re)
        self.le_update_format.setGeometry(QtCore.QRect(9, 16, 31, 20))
        self.le_update_format.setObjectName("le_update_format")
#==========================================================================================gb_output
        self.gb_output = QtWidgets.QGroupBox(parent=self.tan_rename)
        self.gb_output.setGeometry(QtCore.QRect(0, 200, 691, 221))
        self.gb_output.setObjectName("gb_output")
#==========================================================================================txt_output_base
        self.txt_output_base = QtWidgets.QPlainTextEdit(parent=self.gb_output)
        self.txt_output_base.setGeometry(QtCore.QRect(10, 33, 331, 181))
        self.txt_output_base.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.txt_output_base.setObjectName("txt_output_base")
#==========================================================================================txt_output_update
        self.txt_output_update = QtWidgets.QPlainTextEdit(parent=self.gb_output)
        self.txt_output_update.setGeometry(QtCore.QRect(350, 33, 331, 181))
        self.txt_output_update.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.txt_output_update.setObjectName("txt_output_update")
#==========================================================================================lbl_output_base
        self.lbl_output_base = QtWidgets.QLabel(parent=self.gb_output)
        self.lbl_output_base.setGeometry(QtCore.QRect(20, 13, 49, 16))
        self.lbl_output_base.setObjectName("lbl_output_base")
#==========================================================================================lbl_output_update
        self.lbl_output_update = QtWidgets.QLabel(parent=self.gb_output)
        self.lbl_output_update.setGeometry(QtCore.QRect(350, 13, 49, 16))
        self.lbl_output_update.setObjectName("lbl_output_update")
#==========================================================================================tab_dlc_names
        self.all_tabs.addTab(self.tan_rename, "")
        self.tab_dlc_names = QtWidgets.QWidget()
        self.tab_dlc_names.setObjectName("tab_dlc_names")
#==========================================================================================gb_dlc_re
        self.gb_dlc_re = QtWidgets.QGroupBox(parent=self.tab_dlc_names)
        self.gb_dlc_re.setGeometry(QtCore.QRect(0, 0, 691, 411))
        self.gb_dlc_re.setObjectName("gb_dlc_re")
#==========================================================================================btn_dlc_rename_file
        self.btn_dlc_rename_file = QtWidgets.QPushButton(parent=self.gb_dlc_re)
        self.btn_dlc_rename_file.setGeometry(QtCore.QRect(600, 216, 75, 23))
        self.btn_dlc_rename_file.setObjectName("btn_dlc_rename_file")
        self.btn_dlc_rename_file.clicked.connect(lambda: self.rename_game_file('dlc'))
#==========================================================================================le_dlc_version
        self.le_dlc_version = QtWidgets.QLineEdit(parent=self.gb_dlc_re)
        self.le_dlc_version.setGeometry(QtCore.QRect(519, 186, 61, 20))
        self.le_dlc_version.setObjectName("le_dlc_version")
#==========================================================================================lbl_dlc_format
        self.lbl_dlc_format = QtWidgets.QLabel(parent=self.gb_dlc_re)
        self.lbl_format_maker(self.lbl_dlc_format,"lbl_dlc_format",650, 190, 31, 16)
#==========================================================================================btn_dlc_select_folder
        self.btn_dlc_select_folder = QtWidgets.QPushButton(parent=self.gb_dlc_re)
        self.btn_dlc_select_folder.setGeometry(QtCore.QRect(400, 216, 75, 23))
        self.btn_dlc_select_folder.setObjectName("btn_dlc_select_folder")
        self.btn_dlc_select_folder.clicked.connect(lambda:self.select_dlc_folder())
#==========================================================================================lbl_line_13-15
        self.lbl_line_13 = QtWidgets.QLabel(parent=self.gb_dlc_re)
        self.lbl_line_maker(self.lbl_line_13,"lbl_line_13",390, 190, 16, 16)
        self.lbl_line_14 = QtWidgets.QLabel(parent=self.gb_dlc_re)
        self.lbl_line_maker(self.lbl_line_14,"lbl_line_14",511, 190, 16, 16)
        self.lbl_line_15 = QtWidgets.QLabel(parent=self.gb_dlc_re)
        self.lbl_line_maker(self.lbl_line_15,"lbl_line_15",580, 190, 16, 16)
#==========================================================================================le_dlc_site
        self.le_dlc_site = QtWidgets.QLineEdit(parent=self.gb_dlc_re)
        self.le_dlc_site.setGeometry(QtCore.QRect(590, 186, 61, 20))
        self.le_dlc_site.setObjectName("le_dlc_site")
#==========================================================================================le_dlc_title_id
        self.le_dlc_title_id = QtWidgets.QLineEdit(parent=self.gb_dlc_re)
        self.le_dlc_title_id.setGeometry(QtCore.QRect(399, 186, 111, 20))
        self.le_dlc_title_id.setObjectName("le_dlc_title_id")
#==========================================================================================txt_dlc_names
        self.txt_dlc_names = QtWidgets.QPlainTextEdit(parent=self.gb_dlc_re)
        self.txt_dlc_names.setGeometry(QtCore.QRect(10, 20, 381, 381))
        self.txt_dlc_names.setObjectName("txt_dlc_names")
        self.txt_dlc_names.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_dlc_copy_names
        self.btn_dlc_copy_names = QtWidgets.QPushButton(parent=self.gb_dlc_re)
        self.btn_dlc_copy_names.setGeometry(QtCore.QRect(400, 290, 75, 23))
        self.btn_dlc_copy_names.setObjectName("btn_dlc_copy_names")
        self.btn_dlc_copy_names.clicked.connect(lambda: copy(text = self.txt_dlc_names.toPlainText(),note = 'نام DLCها'))
#==========================================================================================le_delete_from_all
        self.le_delete_from_all = QtWidgets.QLineEdit(parent=self.gb_dlc_re)
        self.le_delete_from_all.setGeometry(QtCore.QRect(400, 50, 201, 22))
        self.le_delete_from_all.setObjectName("le_delete_from_all")
#==========================================================================================btn_delete_from_all
        self.btn_delete_from_all = QtWidgets.QPushButton(parent=self.gb_dlc_re)
        self.btn_delete_from_all.setGeometry(QtCore.QRect(610, 50, 75, 24))
        self.btn_delete_from_all.setObjectName("btn_delete_from_all")
        self.btn_delete_from_all.clicked.connect(lambda:self.txt_dlc_names.setPlainText(self.txt_dlc_names.toPlainText().replace(self.le_delete_from_all.text(),''))) #Delete self.le_delete_from_all.text() from self.txt_dlc_names.toPlainText()
#==========================================================================================le_delete_from_left
        self.le_delete_from_left = QtWidgets.QLineEdit(parent=self.gb_dlc_re)
        self.le_delete_from_left.setGeometry(QtCore.QRect(400, 80, 201, 22))
        self.le_delete_from_left.setObjectName("le_delete_from_left")
#==========================================================================================btn_delete_from_left
        self.btn_delete_from_left = QtWidgets.QPushButton(parent=self.gb_dlc_re)
        self.btn_delete_from_left.setGeometry(QtCore.QRect(610, 80, 75, 24))
        self.btn_delete_from_left.setObjectName("btn_delete_from_left")
        self.btn_delete_from_left.clicked.connect(lambda: self.process_lines(mode = 'del_left'))
#==========================================================================================btn_delete_from_right
        self.btn_delete_from_right = QtWidgets.QPushButton(parent=self.gb_dlc_re)
        self.btn_delete_from_right.setGeometry(QtCore.QRect(610, 110, 75, 24))
        self.btn_delete_from_right.setObjectName("btn_delete_from_right")
        self.btn_delete_from_right.clicked.connect(lambda: self.process_lines(mode = 'del_right'))
#==========================================================================================le_delete_from_right
        self.le_delete_from_right = QtWidgets.QLineEdit(parent=self.gb_dlc_re)
        self.le_delete_from_right.setGeometry(QtCore.QRect(400, 110, 201, 22))
        self.le_delete_from_right.setObjectName("le_delete_from_right")
#==========================================================================================lbl_dlc_folder_path
        self.lbl_dlc_folder_path = QtWidgets.QLabel(parent=self.gb_dlc_re)
        self.lbl_dlc_folder_path.setGeometry(QtCore.QRect(400, 253, 281, 20))
        self.lbl_dlc_folder_path.setObjectName("lbl_dlc_folder_path")
#==========================================================================================tab_link_generator
        self.all_tabs.addTab(self.tab_dlc_names, "")
        self.tab_link_generator = QtWidgets.QWidget()
        self.tab_link_generator.setObjectName("tab_link_generator")
#==========================================================================================tab_link_maker_servers
        self.tab_link_maker_servers = QtWidgets.QTabWidget(parent=self.tab_link_generator)
        self.tab_link_maker_servers.setGeometry(QtCore.QRect(10, 0, 691, 411))
        self.tab_link_maker_servers.setObjectName("tab_link_maker_servers")
#==========================================================================================tab_iran
        self.tab_iran = QtWidgets.QWidget()
        self.tab_iran.setObjectName("tab_iran")
#==========================================================================================gb_base_links_fa
        self.gb_base_links_fa = QtWidgets.QGroupBox(parent=self.tab_iran)
        self.gb_base_links_fa.setGeometry(QtCore.QRect(10, 30, 661, 111))
        self.gb_base_links_fa.setObjectName("gb_base_links_fa")
#==========================================================================================txt_base_links_fa
        self.txt_base_links_fa = QtWidgets.QPlainTextEdit(parent=self.gb_base_links_fa)
        self.txt_base_links_fa.setGeometry(QtCore.QRect(10, 40, 561, 61))
        self.txt_base_links_fa.setObjectName("txt_base_links_fa")
        self.txt_base_links_fa.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_base_select_folder_fa
        self.btn_base_select_folder_fa = QtWidgets.QPushButton(parent=self.gb_base_links_fa)
        self.btn_base_select_folder_fa.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.btn_base_select_folder_fa.setObjectName("btn_base_select_folder_fa")
        self.btn_base_select_folder_fa.clicked.connect(lambda: self.downlaod_link_maker(typee = 'base',server = 'fa'))
#==========================================================================================le_base_size_each_file_fa
        self.le_base_size_each_file_fa = QtWidgets.QLineEdit(parent=self.gb_base_links_fa)
        self.le_base_size_each_file_fa.setGeometry(QtCore.QRect(450, 13, 41, 20))
        self.le_base_size_each_file_fa.setObjectName("le_base_size_each_file_fa")
#==========================================================================================lbl_base_size_each_file_fa
        self.lbl_base_size_each_file_fa = QtWidgets.QLabel(parent=self.gb_base_links_fa)
        self.lbl_base_size_each_file_fa.setGeometry(QtCore.QRect(490, 11, 71, 20))
        self.lbl_base_size_each_file_fa.setObjectName("lbl_base_size_each_file_fa")
#==========================================================================================le_base_size_all_file_fa
        self.le_base_size_all_file_fa = QtWidgets.QLineEdit(parent=self.gb_base_links_fa)
        self.le_base_size_all_file_fa.setGeometry(QtCore.QRect(330, 12, 41, 20))
        self.le_base_size_all_file_fa.setObjectName("le_base_size_all_file_fa")
#==========================================================================================lbl_base_size_all_file_fa
        self.lbl_base_size_all_file_fa = QtWidgets.QLabel(parent=self.gb_base_links_fa)
        self.lbl_base_size_all_file_fa.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.lbl_base_size_all_file_fa.setObjectName("lbl_base_size_all_file_fa")
#==========================================================================================le_base_size_last_file_fa
        self.le_base_size_last_file_fa = QtWidgets.QLineEdit(parent=self.gb_base_links_fa)
        self.le_base_size_last_file_fa.setGeometry(QtCore.QRect(210, 12, 41, 20))
        self.le_base_size_last_file_fa.setObjectName("le_base_size_last_file_fa")
#==========================================================================================lbl_base_size_last_file_fa
        self.lbl_base_size_last_file_fa = QtWidgets.QLabel(parent=self.gb_base_links_fa)
        self.lbl_base_size_last_file_fa.setGeometry(QtCore.QRect(250, 10, 71, 20))
        self.lbl_base_size_last_file_fa.setObjectName("lbl_base_size_last_file_fa")
#==========================================================================================gb_update_links_fa
        self.gb_update_links_fa = QtWidgets.QGroupBox(parent=self.tab_iran)
        self.gb_update_links_fa.setGeometry(QtCore.QRect(10, 150, 661, 111))
        self.gb_update_links_fa.setObjectName("gb_update_links_fa")
#==========================================================================================txt_update_links_fa
        self.txt_update_links_fa = QtWidgets.QPlainTextEdit(parent=self.gb_update_links_fa)
        self.txt_update_links_fa.setGeometry(QtCore.QRect(10, 40, 561, 61))
        self.txt_update_links_fa.setObjectName("txt_update_links_fa")
        self.txt_update_links_fa.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_update_select_folder_fa
        self.btn_update_select_folder_fa = QtWidgets.QPushButton(parent=self.gb_update_links_fa)
        self.btn_update_select_folder_fa.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.btn_update_select_folder_fa.setObjectName("btn_update_select_folder_fa")
        self.btn_update_select_folder_fa.clicked.connect(lambda: self.downlaod_link_maker(typee = 'update',server = 'fa'))
#==========================================================================================le_update_size_each_file_fa
        self.le_update_size_each_file_fa = QtWidgets.QLineEdit(parent=self.gb_update_links_fa)
        self.le_update_size_each_file_fa.setGeometry(QtCore.QRect(450, 13, 41, 20))
        self.le_update_size_each_file_fa.setObjectName("le_update_size_each_file_fa")
#==========================================================================================
        self.lbl_update_size_each_file_fa = QtWidgets.QLabel(parent=self.gb_update_links_fa)
        self.lbl_update_size_each_file_fa.setGeometry(QtCore.QRect(490, 11, 71, 20))
        self.lbl_update_size_each_file_fa.setObjectName("lbl_update_size_each_file_fa")
#==========================================================================================le_update_size_all_file_fa
        self.le_update_size_all_file_fa = QtWidgets.QLineEdit(parent=self.gb_update_links_fa)
        self.le_update_size_all_file_fa.setGeometry(QtCore.QRect(330, 12, 41, 20))
        self.le_update_size_all_file_fa.setObjectName("le_update_size_all_file_fa")
#==========================================================================================lbl_update_size_all_file_fa
        self.lbl_update_size_all_file_fa = QtWidgets.QLabel(parent=self.gb_update_links_fa)
        self.lbl_update_size_all_file_fa.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.lbl_update_size_all_file_fa.setObjectName("lbl_update_size_all_file_fa")
#==========================================================================================le_update_size_last_file_fa
        self.le_update_size_last_file_fa = QtWidgets.QLineEdit(parent=self.gb_update_links_fa)
        self.le_update_size_last_file_fa.setGeometry(QtCore.QRect(210, 12, 41, 20))
        self.le_update_size_last_file_fa.setObjectName("le_update_size_last_file_fa")
#==========================================================================================lbl_update_size_last_file_fa
        self.lbl_update_size_last_file_fa = QtWidgets.QLabel(parent=self.gb_update_links_fa)
        self.lbl_update_size_last_file_fa.setGeometry(QtCore.QRect(250, 10, 71, 20))
        self.lbl_update_size_last_file_fa.setObjectName("lbl_update_size_last_file_fa")
#==========================================================================================gb_dlc_links_fa
        self.gb_dlc_links_fa = QtWidgets.QGroupBox(parent=self.tab_iran)
        self.gb_dlc_links_fa.setGeometry(QtCore.QRect(10, 270, 661, 111))
        self.gb_dlc_links_fa.setObjectName("gb_dlc_links_fa")
#==========================================================================================txt_dlc_links_fa
        self.txt_dlc_links_fa = QtWidgets.QPlainTextEdit(parent=self.gb_dlc_links_fa)
        self.txt_dlc_links_fa.setGeometry(QtCore.QRect(10, 40, 561, 61))
        self.txt_dlc_links_fa.setObjectName("txt_dlc_links_fa")
        self.txt_dlc_links_fa.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_dlc_select_folder_fa
        self.btn_dlc_select_folder_fa = QtWidgets.QPushButton(parent=self.gb_dlc_links_fa)
        self.btn_dlc_select_folder_fa.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.btn_dlc_select_folder_fa.setObjectName("btn_dlc_select_folder_fa")
        self.btn_dlc_select_folder_fa.clicked.connect(lambda: self.downlaod_link_maker(typee = 'dlc',server = 'fa'))
#==========================================================================================le_dlc_size_each_file_fa
        self.le_dlc_size_each_file_fa = QtWidgets.QLineEdit(parent=self.gb_dlc_links_fa)
        self.le_dlc_size_each_file_fa.setGeometry(QtCore.QRect(450, 13, 41, 20))
        self.le_dlc_size_each_file_fa.setObjectName("le_dlc_size_each_file_fa")
#==========================================================================================lbl_dlc_size_each_file_fa
        self.lbl_dlc_size_each_file_fa = QtWidgets.QLabel(parent=self.gb_dlc_links_fa)
        self.lbl_dlc_size_each_file_fa.setGeometry(QtCore.QRect(490, 11, 71, 20))
        self.lbl_dlc_size_each_file_fa.setObjectName("lbl_dlc_size_each_file_fa")
#==========================================================================================le_dlc_size_all_file_fa
        self.le_dlc_size_all_file_fa = QtWidgets.QLineEdit(parent=self.gb_dlc_links_fa)
        self.le_dlc_size_all_file_fa.setGeometry(QtCore.QRect(330, 12, 41, 20))
        self.le_dlc_size_all_file_fa.setObjectName("le_dlc_size_all_file_fa")
#==========================================================================================lbl_dlc_size_all_file_fa
        self.lbl_dlc_size_all_file_fa = QtWidgets.QLabel(parent=self.gb_dlc_links_fa)
        self.lbl_dlc_size_all_file_fa.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.lbl_dlc_size_all_file_fa.setObjectName("lbl_dlc_size_all_file_fa")
#==========================================================================================le_dlc_size_last_file_fa
        self.le_dlc_size_last_file_fa = QtWidgets.QLineEdit(parent=self.gb_dlc_links_fa)
        self.le_dlc_size_last_file_fa.setGeometry(QtCore.QRect(210, 12, 41, 20))
        self.le_dlc_size_last_file_fa.setObjectName("le_dlc_size_last_file_fa")
#==========================================================================================lbl_dlc_size_last_file_fa
        self.lbl_dlc_size_last_file_fa = QtWidgets.QLabel(parent=self.gb_dlc_links_fa)
        self.lbl_dlc_size_last_file_fa.setGeometry(QtCore.QRect(250, 10, 71, 20))
        self.lbl_dlc_size_last_file_fa.setObjectName("lbl_dlc_size_last_file_fa")
#==========================================================================================btn_copy_links_fa
        self.btn_copy_links_fa = QtWidgets.QPushButton(parent=self.tab_iran)
        self.btn_copy_links_fa.setGeometry(QtCore.QRect(554, 7, 111, 23))
        self.btn_copy_links_fa.setObjectName("btn_copy_links_fa")
        self.btn_copy_links_fa.clicked.connect(self.copy_dict_links_fa)
#==========================================================================================tab_en
        self.tab_link_maker_servers.addTab(self.tab_iran, "")
        self.tab_en = QtWidgets.QWidget()
        self.tab_en.setObjectName("tab_en")
#==========================================================================================gb_dlc_links_en
        self.gb_dlc_links_en = QtWidgets.QGroupBox(parent=self.tab_en)
        self.gb_dlc_links_en.setGeometry(QtCore.QRect(10, 270, 661, 111))
        self.gb_dlc_links_en.setObjectName("gb_dlc_links_en")
#==========================================================================================txt_dlc_links_en
        self.txt_dlc_links_en = QtWidgets.QPlainTextEdit(parent=self.gb_dlc_links_en)
        self.txt_dlc_links_en.setGeometry(QtCore.QRect(10, 40, 561, 61))
        self.txt_dlc_links_en.setObjectName("txt_dlc_links_en")
        self.txt_dlc_links_en.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_dlc_select_folder_en
        self.btn_dlc_select_folder_en = QtWidgets.QPushButton(parent=self.gb_dlc_links_en)
        self.btn_dlc_select_folder_en.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.btn_dlc_select_folder_en.setObjectName("btn_dlc_select_folder_en")
        self.btn_dlc_select_folder_en.clicked.connect(lambda: self.downlaod_link_maker(typee = 'dlc',server = 'en'))
#==========================================================================================le_dlc_size_each_file_en
        self.le_dlc_size_each_file_en = QtWidgets.QLineEdit(parent=self.gb_dlc_links_en)
        self.le_dlc_size_each_file_en.setGeometry(QtCore.QRect(450, 13, 41, 20))
        self.le_dlc_size_each_file_en.setObjectName("le_dlc_size_each_file_en")
#==========================================================================================lbl_dlc_size_each_file_en
        self.lbl_dlc_size_each_file_en = QtWidgets.QLabel(parent=self.gb_dlc_links_en)
        self.lbl_dlc_size_each_file_en.setGeometry(QtCore.QRect(490, 11, 71, 20))
        self.lbl_dlc_size_each_file_en.setObjectName("lbl_dlc_size_each_file_en")
#==========================================================================================le_dlc_size_all_file_en
        self.le_dlc_size_all_file_en = QtWidgets.QLineEdit(parent=self.gb_dlc_links_en)
        self.le_dlc_size_all_file_en.setGeometry(QtCore.QRect(330, 12, 41, 20))
        self.le_dlc_size_all_file_en.setObjectName("le_dlc_size_all_file_en")
#==========================================================================================lbl_dlc_size_all_file_en
        self.lbl_dlc_size_all_file_en = QtWidgets.QLabel(parent=self.gb_dlc_links_en)
        self.lbl_dlc_size_all_file_en.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.lbl_dlc_size_all_file_en.setObjectName("lbl_dlc_size_all_file_en")
#==========================================================================================le_dlc_size_last_file_en
        self.le_dlc_size_last_file_en = QtWidgets.QLineEdit(parent=self.gb_dlc_links_en)
        self.le_dlc_size_last_file_en.setGeometry(QtCore.QRect(210, 12, 41, 20))
        self.le_dlc_size_last_file_en.setObjectName("le_dlc_size_last_file_en")
#==========================================================================================lbl_dlc_size_last_file_en
        self.lbl_dlc_size_last_file_en = QtWidgets.QLabel(parent=self.gb_dlc_links_en)
        self.lbl_dlc_size_last_file_en.setGeometry(QtCore.QRect(250, 10, 71, 20))
        self.lbl_dlc_size_last_file_en.setObjectName("lbl_dlc_size_last_file_en")
#==========================================================================================btn_copy_links_en
        self.btn_copy_links_en = QtWidgets.QPushButton(parent=self.tab_en)
        self.btn_copy_links_en.setGeometry(QtCore.QRect(554, 7, 111, 23))
        self.btn_copy_links_en.setObjectName("btn_copy_links_en")
        self.btn_copy_links_en.clicked.connect(self.copy_dict_links_en)
#==========================================================================================gb_base_links_en
        self.gb_base_links_en = QtWidgets.QGroupBox(parent=self.tab_en)
        self.gb_base_links_en.setGeometry(QtCore.QRect(10, 30, 661, 111))
        self.gb_base_links_en.setObjectName("gb_base_links_en")
#==========================================================================================txt_base_links_en
        self.txt_base_links_en = QtWidgets.QPlainTextEdit(parent=self.gb_base_links_en)
        self.txt_base_links_en.setGeometry(QtCore.QRect(10, 40, 561, 61))
        self.txt_base_links_en.setObjectName("txt_base_links_en")
        self.txt_base_links_en.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_base_select_folder_en
        self.btn_base_select_folder_en = QtWidgets.QPushButton(parent=self.gb_base_links_en)
        self.btn_base_select_folder_en.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.btn_base_select_folder_en.setObjectName("btn_base_select_folder_en")
        self.btn_base_select_folder_en.clicked.connect(lambda: self.downlaod_link_maker(typee = 'base',server = 'en'))
#==========================================================================================le_base_size_each_file_en
        self.le_base_size_each_file_en = QtWidgets.QLineEdit(parent=self.gb_base_links_en)
        self.le_base_size_each_file_en.setGeometry(QtCore.QRect(450, 13, 41, 20))
        self.le_base_size_each_file_en.setObjectName("le_base_size_each_file_en")
#==========================================================================================lbl_base_size_each_file_en
        self.lbl_base_size_each_file_en = QtWidgets.QLabel(parent=self.gb_base_links_en)
        self.lbl_base_size_each_file_en.setGeometry(QtCore.QRect(490, 11, 71, 20))
        self.lbl_base_size_each_file_en.setObjectName("lbl_base_size_each_file_en")
#==========================================================================================le_base_size_all_file_en
        self.le_base_size_all_file_en = QtWidgets.QLineEdit(parent=self.gb_base_links_en)
        self.le_base_size_all_file_en.setGeometry(QtCore.QRect(330, 12, 41, 20))
        self.le_base_size_all_file_en.setObjectName("le_base_size_all_file_en")
#==========================================================================================lbl_base_size_all_file_en
        self.lbl_base_size_all_file_en = QtWidgets.QLabel(parent=self.gb_base_links_en)
        self.lbl_base_size_all_file_en.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.lbl_base_size_all_file_en.setObjectName("lbl_base_size_all_file_en")
#==========================================================================================le_base_size_last_file_en
        self.le_base_size_last_file_en = QtWidgets.QLineEdit(parent=self.gb_base_links_en)
        self.le_base_size_last_file_en.setGeometry(QtCore.QRect(210, 12, 41, 20))
        self.le_base_size_last_file_en.setObjectName("le_base_size_last_file_en")
#==========================================================================================lbl_base_size_last_file_en
        self.lbl_base_size_last_file_en = QtWidgets.QLabel(parent=self.gb_base_links_en)
        self.lbl_base_size_last_file_en.setGeometry(QtCore.QRect(250, 10, 71, 20))
        self.lbl_base_size_last_file_en.setObjectName("lbl_base_size_last_file_en")
#==========================================================================================gb_update_links_en
        self.gb_update_links_en = QtWidgets.QGroupBox(parent=self.tab_en)
        self.gb_update_links_en.setGeometry(QtCore.QRect(10, 150, 661, 111))
        self.gb_update_links_en.setObjectName("gb_update_links_en")
#==========================================================================================txt_update_links_en
        self.txt_update_links_en = QtWidgets.QPlainTextEdit(parent=self.gb_update_links_en)
        self.txt_update_links_en.setGeometry(QtCore.QRect(10, 40, 561, 61))
        self.txt_update_links_en.setObjectName("txt_update_links_en")
        self.txt_update_links_en.setWordWrapMode(QtGui.QTextOption.WrapMode.NoWrap)
#==========================================================================================btn_update_select_folder_en
        self.btn_update_select_folder_en = QtWidgets.QPushButton(parent=self.gb_update_links_en)
        self.btn_update_select_folder_en.setGeometry(QtCore.QRect(580, 60, 75, 23))
        self.btn_update_select_folder_en.setObjectName("btn_update_select_folder_en")
        self.btn_update_select_folder_en.clicked.connect(lambda: self.downlaod_link_maker(typee = 'update',server = 'en'))
#==========================================================================================le_update_size_each_file_en
        self.le_update_size_each_file_en = QtWidgets.QLineEdit(parent=self.gb_update_links_en)
        self.le_update_size_each_file_en.setGeometry(QtCore.QRect(450, 13, 41, 20))
        self.le_update_size_each_file_en.setObjectName("le_update_size_each_file_en")
#==========================================================================================lbl_update_size_each_file_en
        self.lbl_update_size_each_file_en = QtWidgets.QLabel(parent=self.gb_update_links_en)
        self.lbl_update_size_each_file_en.setGeometry(QtCore.QRect(490, 11, 71, 20))
        self.lbl_update_size_each_file_en.setObjectName("lbl_update_size_each_file_en")
#==========================================================================================le_update_size_all_file_en
        self.le_update_size_all_file_en = QtWidgets.QLineEdit(parent=self.gb_update_links_en)
        self.le_update_size_all_file_en.setGeometry(QtCore.QRect(330, 12, 41, 20))
        self.le_update_size_all_file_en.setObjectName("le_update_size_all_file_en")
#==========================================================================================lbl_update_size_all_file_en
        self.lbl_update_size_all_file_en = QtWidgets.QLabel(parent=self.gb_update_links_en)
        self.lbl_update_size_all_file_en.setGeometry(QtCore.QRect(370, 10, 71, 20))
        self.lbl_update_size_all_file_en.setObjectName("lbl_update_size_all_file_en")
#==========================================================================================le_update_size_last_file_en
        self.le_update_size_last_file_en = QtWidgets.QLineEdit(parent=self.gb_update_links_en)
        self.le_update_size_last_file_en.setGeometry(QtCore.QRect(210, 12, 41, 20))
        self.le_update_size_last_file_en.setObjectName("le_update_size_last_file_en")
#==========================================================================================lbl_update_size_last_file_en
        self.lbl_update_size_last_file_en = QtWidgets.QLabel(parent=self.gb_update_links_en)
        self.lbl_update_size_last_file_en.setGeometry(QtCore.QRect(250, 10, 71, 20))
        self.lbl_update_size_last_file_en.setObjectName("lbl_update_size_last_file_en")
#==========================================================================================tab_setting
        self.cb_select_server_en = QtWidgets.QComboBox(parent=self.tab_en)
        self.cb_select_server_en.setGeometry(QtCore.QRect(20, 7, 271, 22))
        self.cb_select_server_en.setObjectName("cb_select_server_en")
        for i in range(len(list_server)):
            self.cb_select_server_en.addItem("")
        self.cb_select_server_en.currentIndexChanged.connect(lambda:self.download_en_tab_sim(self.cb_select_server_en.currentIndex()))
#==========================================================================================
        self.tab_link_maker_servers.addTab(self.tab_en, "")
        self.all_tabs.addTab(self.tab_link_generator, "")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
#==========================================================================================lbl_server_fa
        self.lbl_server_fa = QtWidgets.QLabel(parent=self.tab_setting)
        self.lbl_server_fa.setGeometry(QtCore.QRect(600, 20, 91, 20))
        self.lbl_server_fa.setObjectName("lbl_server_fa")
#==========================================================================================le_server_fa
        self.le_server_fa = QtWidgets.QLineEdit(parent=self.tab_setting)
        self.le_server_fa.setGeometry(QtCore.QRect(10, 50, 681, 20))
        self.le_server_fa.setObjectName("le_server_fa")
        self.le_server_fa.setText(list_settings[0])
#==========================================================================================btn_save_settings
        self.btn_save_settings = QtWidgets.QPushButton(parent=self.tab_setting)
        self.btn_save_settings.setGeometry(QtCore.QRect(20, 150, 75, 24))
        self.btn_save_settings.setObjectName("btn_save_settings")
        self.btn_save_settings.clicked.connect(self.save_settings)
#==========================================================================================lbl_game_path
        self.lbl_game_path = QtWidgets.QLabel(parent=self.tab_setting)
        self.lbl_game_path.setGeometry(QtCore.QRect(590, 80, 101, 20))
        self.lbl_game_path.setObjectName("lbl_game_path")
#==========================================================================================le_game_path
        self.le_game_path = QtWidgets.QLineEdit(parent=self.tab_setting)
        self.le_game_path.setGeometry(QtCore.QRect(10, 110, 681, 20))
        self.le_game_path.setObjectName("le_game_path")
        self.le_game_path.setText(list_settings[1].replace('\\','/'))
#==========================================================================================lbl_notify
        self.all_tabs.addTab(self.tab_setting, "")
        self.lbl_notify = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_notify.setGeometry(QtCore.QRect(10, 460, 701, 61))
        font = QtGui.QFont()
        font.setBold(True)
        self.lbl_notify.setFont(font)
        self.lbl_notify.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_notify.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.lbl_notify.setLineWidth(0)
        self.lbl_notify.setMidLineWidth(1)
        self.lbl_notify.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_notify.setObjectName("lbl_notify")
#==========================================================================================menubar
        link_maker.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=link_maker)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 21))
        self.menubar.setObjectName("menubar")
#==========================================================================================statusbar
        link_maker.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=link_maker)
        self.statusbar.setObjectName("statusbar")
#==========================================================================================
        link_maker.setStatusBar(self.statusbar)

        self.retranslateUi(link_maker)
        self.all_tabs.setCurrentIndex(0)
        self.tab_link_maker_servers.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(link_maker)

    def retranslateUi(self, link_maker):
        _translate = QtCore.QCoreApplication.translate
        link_maker.setWindowTitle(_translate("link_maker", "Link Maker v1.00"))
        self.gb_base_re.setTitle(_translate("link_maker", "Base"))
        self.btn_base_rename_file.setText(_translate("link_maker", "تغییر نام فایل"))
        self.le_base_version.setText(_translate("link_maker", ""))
        self.le_base_dv.setText(_translate("link_maker", ""))
        self.btn_base_select_file.setText(_translate("link_maker", "انتخاب فایل"))
        self.le_base_site.setText(_translate("link_maker", "nintenland"))
        self.le_base_sdkv.setText(_translate("link_maker", ""))
        self.le_base_title_id.setText(_translate("link_maker", ""))
        self.le_base_name.setText(_translate("link_maker", ""))
        self.le_base_format.setText(_translate("link_maker", ""))
        self.gb_update_re.setTitle(_translate("link_maker", "Update"))
        self.btn_update_rename_file.setText(_translate("link_maker", "تغییر نام فایل"))
        self.le_update_version.setText(_translate("link_maker", ""))
        self.le_update_dv.setText(_translate("link_maker", ""))
        self.btn_update_select_file.setText(_translate("link_maker", "انتخاب فایل"))
        self.le_update_site.setText(_translate("link_maker", "nintenland"))
        self.le_update_sdkv.setText(_translate("link_maker", ""))
        self.le_update_title_id.setText(_translate("link_maker", ""))
        self.le_update_name.setText(_translate("link_maker", ""))
        self.le_update_format.setText(_translate("link_maker", ""))
        self.gb_output.setTitle(_translate("link_maker", "Output"))
        self.lbl_output_base.setText(_translate("link_maker", "Base"))
        self.lbl_output_update.setText(_translate("link_maker", "Update"))
        self.all_tabs.setTabText(self.all_tabs.indexOf(self.tan_rename), _translate("link_maker", "تغییر نام"))
        self.gb_dlc_re.setTitle(_translate("link_maker", "DLC"))
        self.btn_dlc_rename_file.setText(_translate("link_maker", "تغییر نام فایل"))
        self.btn_dlc_select_folder.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_dlc_site.setText(_translate("link_maker", "nintenland"))
        self.le_dlc_title_id.setText(_translate("link_maker", ""))
        self.btn_dlc_copy_names.setText(_translate("link_maker", "کپی"))
        self.btn_delete_from_all.setText(_translate("link_maker", "حذف از کل"))
        self.btn_delete_from_left.setText(_translate("link_maker", "حذف از چپ"))
        self.btn_delete_from_right.setText(_translate("link_maker", "حذف از راست"))
        self.all_tabs.setTabText(self.all_tabs.indexOf(self.tab_dlc_names), _translate("link_maker", "نام‌های دی‌ال‌سی"))
        self.gb_base_links_fa.setTitle(_translate("link_maker", "Base"))
        self.btn_base_select_folder_fa.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_base_size_each_file_fa.setText(_translate("link_maker", ""))
        self.lbl_base_size_each_file_fa.setText(_translate("link_maker", "حجم هر پارت:"))
        self.le_base_size_all_file_fa.setText(_translate("link_maker", ""))
        self.lbl_base_size_all_file_fa.setText(_translate("link_maker", "حجم کل بازی:"))
        self.le_base_size_last_file_fa.setText(_translate("link_maker", ""))
        self.lbl_base_size_last_file_fa.setText(_translate("link_maker", "حجم پارت آخر:"))
        self.gb_update_links_fa.setTitle(_translate("link_maker", "Update"))
        self.btn_update_select_folder_fa.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_update_size_each_file_fa.setText(_translate("link_maker", ""))
        self.lbl_update_size_each_file_fa.setText(_translate("link_maker", "حجم هر پارت:"))
        self.le_update_size_all_file_fa.setText(_translate("link_maker", ""))
        self.lbl_update_size_all_file_fa.setText(_translate("link_maker", "حجم کل بازی:"))
        self.le_update_size_last_file_fa.setText(_translate("link_maker", ""))
        self.lbl_update_size_last_file_fa.setText(_translate("link_maker", "حجم پارت آخر:"))
        self.gb_dlc_links_fa.setTitle(_translate("link_maker", "DLC"))
        self.btn_dlc_select_folder_fa.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_dlc_size_each_file_fa.setText(_translate("link_maker", ""))
        self.lbl_dlc_size_each_file_fa.setText(_translate("link_maker", "حجم هر پارت:"))
        self.le_dlc_size_all_file_fa.setText(_translate("link_maker", ""))
        self.lbl_dlc_size_all_file_fa.setText(_translate("link_maker", "حجم کل بازی:"))
        self.le_dlc_size_last_file_fa.setText(_translate("link_maker", ""))
        self.lbl_dlc_size_last_file_fa.setText(_translate("link_maker", "حجم پارت آخر:"))
        self.btn_copy_links_fa.setText(_translate("link_maker", "کپی لینک های ایران"))
        self.tab_link_maker_servers.setTabText(self.tab_link_maker_servers.indexOf(self.tab_iran), _translate("link_maker", "ایران"))
        self.gb_dlc_links_en.setTitle(_translate("link_maker", "DLC"))
        self.btn_dlc_select_folder_en.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_dlc_size_each_file_en.setText(_translate("link_maker", ""))
        self.lbl_dlc_size_each_file_en.setText(_translate("link_maker", "حجم هر پارت:"))
        self.le_dlc_size_all_file_en.setText(_translate("link_maker", ""))
        self.lbl_dlc_size_all_file_en.setText(_translate("link_maker", "حجم کل بازی:"))
        self.le_dlc_size_last_file_en.setText(_translate("link_maker", ""))
        self.lbl_dlc_size_last_file_en.setText(_translate("link_maker", "حجم پارت آخر:"))
        self.btn_copy_links_en.setText(_translate("link_maker", "کپی لینک های خارج"))
        self.gb_base_links_en.setTitle(_translate("link_maker", "Base"))
        self.btn_base_select_folder_en.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_base_size_each_file_en.setText(_translate("link_maker", ""))
        self.lbl_base_size_each_file_en.setText(_translate("link_maker", "حجم هر پارت:"))
        self.le_base_size_all_file_en.setText(_translate("link_maker", ""))
        self.lbl_base_size_all_file_en.setText(_translate("link_maker", "حجم کل بازی:"))
        self.le_base_size_last_file_en.setText(_translate("link_maker", ""))
        self.lbl_base_size_last_file_en.setText(_translate("link_maker", "حجم پارت آخر:"))
        self.gb_update_links_en.setTitle(_translate("link_maker", "Update"))
        self.btn_update_select_folder_en.setText(_translate("link_maker", "انتخاب فولدر"))
        self.le_update_size_each_file_en.setText(_translate("link_maker", ""))
        self.lbl_update_size_each_file_en.setText(_translate("link_maker", "حجم هر پارت:"))
        self.le_update_size_all_file_en.setText(_translate("link_maker", ""))
        self.lbl_update_size_all_file_en.setText(_translate("link_maker", "حجم کل بازی:"))
        self.le_update_size_last_file_en.setText(_translate("link_maker", ""))
        self.lbl_update_size_last_file_en.setText(_translate("link_maker", "حجم پارت آخر:"))
        for i in range(len(list_server)):
                self.cb_select_server_en.setItemText(i, _translate("link_maker", list_server[i]))
        self.tab_link_maker_servers.setTabText(self.tab_link_maker_servers.indexOf(self.tab_en), _translate("link_maker", "خارج"))
        self.all_tabs.setTabText(self.all_tabs.indexOf(self.tab_link_generator), _translate("link_maker", "لینک ساز"))
        self.lbl_server_fa.setText(_translate("link_maker", "لینک سرور ایران"))
        self.btn_save_settings.setText(_translate("link_maker", "ذخیره"))
        self.lbl_game_path.setText(_translate("link_maker", "مسیر پیشفرض بازی"))
        self.all_tabs.setTabText(self.all_tabs.indexOf(self.tab_setting), _translate("link_maker", "تنظیمات"))
        self.lbl_notify.setText(_translate("link_maker", "Notfication"))

    def lbl_line_maker(self,lbl_line,obj_name,a, b, c, d):
        lbl_line.setGeometry(QtCore.QRect(a, b, c, d))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        lbl_line.setFont(font)
        lbl_line.setObjectName(obj_name)
        lbl_line.setText(QtCore.QCoreApplication.translate("link_maker",'-'))

    def lbl_format_maker(self,lbl_format,obj_name,a, b, c, d):
        lbl_format.setGeometry(QtCore.QRect(a, b, c, d))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        lbl_format.setFont(font)
        lbl_format.setObjectName(obj_name)
        lbl_format.setText(QtCore.QCoreApplication.translate("link_maker", '.nsp'))

    def download_en_tab_sim(self,index):
        '''
        dict_en_server_link[str_server_en_index][0-2] txt_links_en
        dict_en_server_link[str_server_en_index][3-5] size_each_file_en
        dict_en_server_link[str_server_en_index][6-8] size_all_file_en
        dict_en_server_link[str_server_en_index][9-11] size_last_file_en
        '''
        global dict_en_server_link,server_en_index
        dict_en_server_link.update({str(server_en_index):[self.txt_base_links_en.toPlainText(),self.txt_update_links_en.toPlainText(),self.txt_dlc_links_en.toPlainText(),
                                                        self.le_base_size_each_file_en.text(),self.le_update_size_each_file_en.text(),self.le_dlc_size_each_file_en.text(),
                                                        self.le_base_size_all_file_en.text(),self.le_update_size_all_file_en.text(),self.le_dlc_size_all_file_en.text(),
                                                        self.le_base_size_last_file_en.text(),self.le_update_size_last_file_en.text(),self.le_dlc_size_last_file_en.text()]})
        server_en_index=index
        str_server_en_index = str(server_en_index)

        self.txt_base_links_en.clear()
        self.txt_update_links_en.clear()
        self.txt_dlc_links_en.clear()

        self.le_base_size_each_file_en.clear()
        self.le_update_size_each_file_en.clear()
        self.le_dlc_size_each_file_en.clear()

        self.le_base_size_all_file_en.clear()
        self.le_update_size_all_file_en.clear()
        self.le_dlc_size_all_file_en.clear()

        self.le_base_size_last_file_en.clear()
        self.le_update_size_last_file_en.clear()
        self.le_dlc_size_last_file_en.clear()

        if str_server_en_index in dict_en_server_link.keys():
                self.txt_base_links_en.setPlainText(dict_en_server_link[str_server_en_index][0])
                self.txt_update_links_en.setPlainText(dict_en_server_link[str_server_en_index][1])
                self.txt_dlc_links_en.setPlainText(dict_en_server_link[str_server_en_index][2])

                self.le_base_size_each_file_en.setText(dict_en_server_link[str_server_en_index][3])
                self.le_update_size_each_file_en.setText(dict_en_server_link[str_server_en_index][4])
                self.le_dlc_size_each_file_en.setText(dict_en_server_link[str_server_en_index][5])

                self.le_base_size_all_file_en.setText(dict_en_server_link[str_server_en_index][6])
                self.le_update_size_all_file_en.setText(dict_en_server_link[str_server_en_index][7])
                self.le_dlc_size_all_file_en.setText(dict_en_server_link[str_server_en_index][8])

                self.le_base_size_last_file_en.setText(dict_en_server_link[str_server_en_index][9])
                self.le_update_size_last_file_en.setText(dict_en_server_link[str_server_en_index][10])
                self.le_dlc_size_last_file_en.setText(dict_en_server_link[str_server_en_index][11])

    def choose_a_file(self, folder_path = '',top_title = 'انتخاب بیس',file_format = "Switch file (*.nsp *.xci)"):
        #folder_path = basedir1() + "/Pics/" + base_address
        if os.path.exists(folder_path):
                fname = QtWidgets.QFileDialog.getOpenFileName(None, top_title, folder_path, file_format)
                return fname[0]
        else:
                fname = QtWidgets.QFileDialog.getOpenFileName(None, top_title, 'Desktop', file_format)
                return fname[0]

    def choose_folder(self,folder_path = "",top_title = "DLC انتخاب پوشه"):
        try:
                #folder_path = basedir1() + "/Pics/" + base_address
                if os.path.exists(folder_path):
                        fpath = QtWidgets.QFileDialog.getExistingDirectory(None,top_title,folder_path)
                else:
                        fpath = QtWidgets.QFileDialog.getExistingDirectory(None,top_title,'Desktop',)
                return fpath
        except:
                pass

    def choose_game_file(self,typee = "base"):
        notify('')
        if typee == "base":
                le_format = self.le_base_format
                le_name = self.le_base_name
                le_title_id = self.le_base_title_id
                le_version = self.le_base_version
                le_sdkv = self.le_base_sdkv
                le_dv = self.le_base_dv
                top_title = "بازی Base انتخاب"
                le_file_path = self.lbl_base_file_path
                txt_output = self.txt_output_base
        elif typee == "update":
                le_format = self.le_update_format
                le_name = self.le_update_name
                le_title_id = self.le_update_title_id
                le_version = self.le_update_version
                le_sdkv = self.le_update_sdkv
                le_dv = self.le_update_dv
                top_title = "بازی Update انتخاب"
                le_file_path = self.lbl_update_file_path
                txt_output = self.txt_output_update
        file_path = self.choose_a_file(folder_path = list_settings[1],top_title = top_title, file_format = "Switch file (*.nsp *.xci)")
        list_title_info = nx_game_info(exe_path = nx_info_path, game_path = file_path)
        dict_title_info = list_title_info[0]
        le_file_path.setText(file_path)
        try:
                if dict_type[dict_title_info['Type']] == typee:
                        le_format.setText(file_path[-3:].upper())
                        le_name.setText(dotify(dict_title_info['Title Name']))
                        le_title_id.setText(dict_title_info['Title ID'])
                        le_version.setText('v'+dict_title_info['Version'])
                        le_dv.setText('dv'+dict_title_info['Display Version'])
                        le_sdkv.setText('sv'+dict_title_info['System Version'])
                        self.size_puter(dict_type[dict_title_info['Type']],dict_title_info['Filesize'].replace(' ',''))
                        txt_output.setPlainText(list_title_info[1])
                else:
                        notify('نوع فایل انتخاب شده اشتباه است')
        except:
                pass
        # 

    def size_puter(self,typee = 'base',size = ''):
        if typee == 'base':
                self.le_base_size_all_file_fa.setText(size)
                self.le_base_size_all_file_en.setText(size)
                
        elif typee == 'update':
                self.le_update_size_all_file_fa.setText(size)
                self.le_update_size_all_file_en.setText(size)
        elif typee == 'dlc':
                self.le_dlc_size_all_file_fa.setText(size)
                self.le_dlc_size_all_file_en.setText(size)
        self.update_size_all_file_en(typee)

    def select_dlc_folder(self):
        self.lbl_dlc_folder_path.setText(self.choose_folder(list_settings[1]))
        find_nsp_and_xci_files(self.lbl_dlc_folder_path.text())

    def process_lines(self, mode = 'del_left'):
        lines = self.txt_dlc_names.toPlainText().splitlines()
        processed_lines = []
        for line in lines:
                QtWidgets.QApplication.processEvents()
                if mode == 'del_left':
                        left_text = self.le_delete_from_left.text()
                        position = line.find(left_text)
                        if position != -1:
                                processed_line = line[position + len(left_text):]
                        else:
                                processed_line = line
                elif mode == 'del_right':
                        right_text = self.le_delete_from_right.text()
                        position = line.find(right_text)
                        if position != -1:
                                processed_line = line[:position]
                        else:
                                processed_line = line
                else:
                        processed_line = line
                processed_lines.append(processed_line)
        self.txt_dlc_names.setPlainText('\n'.join(processed_lines))

    def rename_game_file(self,typee = "base"):
        global list_dlc,dict_dlc
        if typee == 'base' or typee =='update':
                if typee == "base":
                        le_format = self.le_base_format
                        le_name = self.le_base_name
                        le_title_id = self.le_base_title_id
                        le_version = self.le_base_version
                        le_sdkv = self.le_base_sdkv
                        le_dv = self.le_base_dv
                        le_file_path = self.lbl_base_file_path
                        le_site_path = self.le_base_site
                elif typee == "update":
                        le_format = self.le_update_format
                        le_name = self.le_update_name
                        le_title_id = self.le_update_title_id
                        le_version = self.le_update_version
                        le_sdkv = self.le_update_sdkv
                        le_dv = self.le_update_dv
                        le_file_path = self.lbl_update_file_path
                        le_site_path = self.le_update_site
                if le_name.text() != '':
                        file_name = le_format.text()+'-'+le_name.text()+'-'+le_title_id.text()+'-'+le_version.text()+'-'+le_sdkv.text()+'-'+le_dv.text()+'-'+le_site_path.text()
                        le_file_path.setText(rename_file(le_file_path.text(),file_name))
                        notify("تغییر نام با موفقیت انجام شد")
        elif typee == 'dlc':
                try:
                        #dict_dlc[file[:-4]] = [dlc_path, dict_dlc_info['Title ID'], "v"+dict_dlc_info['Version']]
                        txt_dlc_pt = self.txt_dlc_names.toPlainText()
                        if txt_dlc_pt != '':
                                list_dlc_pt = txt_dlc_pt.splitlines()
                                len_list_dlc = len(list_dlc)
                                if len(list_dlc_pt) == len_list_dlc:
                                        for i in range(len_list_dlc):
                                                QtWidgets.QApplication.processEvents()
                                                if list_dlc_pt[i] != list_dlc[i]:
                                                        path_dlc = dict_dlc[list_dlc[i]][0]
                                                        file_name = dotify(list_dlc_pt[i])+'-'+dict_dlc[list_dlc[i]][1]+'-'+dict_dlc[list_dlc[i]][2]+'-'+self.le_dlc_site.text()
                                                        path_dlc = rename_file(path_dlc,file_name)
                                                        dict_dlc[list_dlc_pt[i]] = [path_dlc, dict_dlc[list_dlc[i]][1], "v"+dict_dlc[list_dlc[i]][2]]
                                                        del dict_dlc[list_dlc[i]]
                                        list_dlc.clear()
                                        list_dlc = list(dict_dlc.keys())
                                        dlc_folder_size = folder_size(self.lbl_dlc_folder_path.text())
                                        self.size_puter(typee = 'dlc',size = dlc_folder_size)
                                        notify("تغییر نام DLC با موفقیت انجام شد")
                                else:
                                        notify('خطوط نام ها با تعداد دی ال سی ها برابر نیست')
                except Exception as e:
                        # نمایش خطا در یک پنجره پیام
                        error_msg = f"Error: {str(e)}"
                        msg_box = QtWidgets.QMessageBox()
                        msg_box.setIcon(QtWidgets.QMessageBox.Icon.Critical)
                        msg_box.setWindowTitle("Error")
                        msg_box.setText(error_msg)
                        msg_box.exec()

    def save_settings(self):
        global list_settings
        settings = self.le_server_fa.text() +'\n'+ self.le_game_path.text().replace('\\','/')
        txt_saver(settings,true_path("/setting/settings.in"))
        list_settings.clear()
        list_settings = settings.splitlines()
        notify('تنظیمات با موفقیت ذخیره شد')

    def downlaod_link_maker(self,typee = 'base',server = 'fa'):
        server_path = self.le_server_fa.text()
        if server_path != '':
                if typee == 'base':
                        le_size_each_file_fa = self.le_base_size_each_file_fa
                        le_size_last_file_fa = self.le_base_size_last_file_fa
                        le_size_each_file_en = self.le_base_size_each_file_en
                        le_size_last_file_en = self.le_base_size_last_file_en
                        txt_links_fa = self.txt_base_links_fa
                        txt_links_en = self.txt_base_links_en
                        title = "Base انتخاب"
                elif typee == 'update':
                        le_size_each_file_fa = self.le_update_size_each_file_fa
                        le_size_last_file_fa = self.le_update_size_last_file_fa
                        le_size_each_file_en = self.le_update_size_each_file_en
                        le_size_last_file_en = self.le_update_size_last_file_en
                        txt_links_fa = self.txt_update_links_fa
                        txt_links_en = self.txt_update_links_en
                        title = "Update انتخاب"
                elif typee == 'dlc':
                        le_size_each_file_fa = self.le_dlc_size_each_file_fa
                        le_size_last_file_fa = self.le_dlc_size_last_file_fa
                        le_size_each_file_en = self.le_dlc_size_each_file_en
                        le_size_last_file_en = self.le_dlc_size_last_file_en
                        txt_links_fa = self.txt_dlc_links_fa
                        txt_links_en = self.txt_dlc_links_en
                        title = "DLC انتخاب"
                folder_path = self.choose_folder(list_settings[1],title)
                list_rar_files = find_rar_files(folder_path)
                links = ''
                len_list_rar_files = len(list_rar_files)
                if list_rar_files != []:
                        if server == 'fa':
                                for i in range(len_list_rar_files):
                                        QtWidgets.QApplication.processEvents()
                                        second_folder_path = folder_path.replace(list_rar_files[i][1],'')
                                        first_folder_name = os.path.basename(second_folder_path[:-1])
                                        if i == 0:
                                                file_size = convert_bytes(os.path.getsize(second_folder_path+'/'+list_rar_files[i][0]))
                                                le_size_each_file_fa.setText(file_size)
                                        if i != len_list_rar_files-1:
                                                links = links + server_path + first_folder_name+'/'+ list_rar_files[i][0] + '\n'
                                        elif i == len_list_rar_files-1:
                                                file_size = convert_bytes(os.path.getsize(second_folder_path+'/'+list_rar_files[i][0]))
                                                links = links + server_path + first_folder_name+'/'+ list_rar_files[i][0]
                                                le_size_last_file_fa.setText(file_size)
                                        txt_links_fa.setPlainText(links)
                        elif server == 'en':
                                second_folder_path = folder_path.replace(list_rar_files[0][1],'')
                                first_folder_name = os.path.basename(second_folder_path[:-1])
                                file_size = convert_bytes(os.path.getsize(second_folder_path+'/'+list_rar_files[0][0]))
                                le_size_each_file_en.setText(file_size)
                                file_size = convert_bytes(os.path.getsize(second_folder_path+'/'+list_rar_files[len_list_rar_files-1][0]))
                                le_size_last_file_en.setText(file_size)
                                txt_links_en.setPlainText(str(len_list_rar_files)+'\n')
                                self.update_dict_en_server_link()
                else:
                        notify('مسیر اشتباه انتخاب شده')

    def update_dict_en_server_link(self):
        global dict_en_server_link
        str_server_en_index = str(self.cb_select_server_en.currentIndex())
        dict_en_server_link.update({str_server_en_index:[self.txt_base_links_en.toPlainText(),self.txt_update_links_en.toPlainText(),self.txt_dlc_links_en.toPlainText(),
                                                        self.le_base_size_each_file_en.text(),self.le_update_size_each_file_en.text(),self.le_dlc_size_each_file_en.text(),
                                                        self.le_base_size_all_file_en.text(),self.le_update_size_all_file_en.text(),self.le_dlc_size_all_file_en.text(),
                                                        self.le_base_size_last_file_en.text(),self.le_update_size_last_file_en.text(),self.le_dlc_size_last_file_en.text()]})

    def update_size_all_file_en(self,typee = 'base'):
        #dict_en_server_link[str_server_en_index][6-8] 
        global dict_en_server_link
        self.update_dict_en_server_link()
        if typee == 'base':
                le_id = 6
                le_size_all_file_en = self.le_base_size_all_file_en
        elif typee == 'update':
                le_id = 7
                le_size_all_file_en = self.le_update_size_all_file_en
        elif typee == 'dlc':
                le_id = 8
                le_size_all_file_en = self.le_dlc_size_all_file_en
        for i in range(len(list_server)):
                QtWidgets.QApplication.processEvents()
                current_values = dict_en_server_link[str(i)]
                current_values[le_id] = le_size_all_file_en.text()
                dict_en_server_link[str(i)] = current_values

    def insert_size_in_link_list(self,input_link_list = list ,link_each_part_size = '',link_all_size = '',link_last_part_size_or_len_links='',file_version='',file_format='',title_id = '' ):
        top_info = f'x1"{link_each_part_size}"1x,x2"{link_all_size}"2x,x3"{link_last_part_size_or_len_links}"3x,x4"{file_version}"4x,x5"{file_format}"5x,x6"{title_id}"6x'
        input_link_list.insert(0,top_info)
        return Jamelist(input_link_list)

    def copy_dict_links_fa(self):
        if self.txt_base_links_fa.toPlainText() != '':
                base = self.insert_size_in_link_list(self.txt_base_links_fa.toPlainText().splitlines(),
                                        self.le_base_size_each_file_fa.text(),
                                        self.le_base_size_all_file_fa.text(),
                                        self.le_base_size_last_file_fa.text(),
                                        self.le_base_version.text(),
                                        self.le_base_format.text(),
                                        self.le_base_title_id.text())
        else:
                base = ''
        if self.txt_update_links_fa.toPlainText() != '':
                update = self.insert_size_in_link_list(self.txt_update_links_fa.toPlainText().splitlines(),
                                        self.le_update_size_each_file_fa.text(),
                                        self.le_update_size_all_file_fa.text(),
                                        self.le_update_size_last_file_fa.text(),
                                        self.le_update_version.text(),
                                        self.le_update_format.text(),
                                        self.le_update_title_id.text())
        else:
                update = ''
        if self.txt_dlc_links_fa.toPlainText() != '':
                dlc = self.insert_size_in_link_list(self.txt_dlc_links_fa.toPlainText().splitlines(),
                                        self.le_dlc_size_each_file_fa.text(),
                                        self.le_dlc_size_all_file_fa.text(),
                                        self.le_dlc_size_last_file_fa.text(),
                                        self.le_dlc_version.text(),
                                        'NSP',
                                        self.le_dlc_title_id.text())
        else:
                dlc = ''
        dict_full_links = {'ir_server':[base,update,dlc]}
        copy(str(dict_full_links),'لینک سرور ایران با موفقیت کپی شد')

    def copy_dict_links_en(self):
        """                
        link_each_part_size='' # x1
        link_all_size='' # x2
        len_links='' # x3(str)  تعداد لینک های اینگلیسی
        file_version=''# x4
        file_format=''# x5
        title_id = ''# x6
        """
        '''
        dict_en_server_link[str_server_en_index][3-5] size_each_file_en
        dict_en_server_link[str_server_en_index][6-8] size_all_file_en
        dict_en_server_link[str_server_en_index][9-11] size_last_file_en
        base 3 6 9
        update 4 7 10
        dlc 5 8 11
        '''
        # list_links[0] = len_links, len_links[1] = link
        dict_en_server_link.update({str(server_en_index):[self.txt_base_links_en.toPlainText(),self.txt_update_links_en.toPlainText(),self.txt_dlc_links_en.toPlainText(),
                                                        self.le_base_size_each_file_en.text(),self.le_update_size_each_file_en.text(),self.le_dlc_size_each_file_en.text(),
                                                        self.le_base_size_all_file_en.text(),self.le_update_size_all_file_en.text(),self.le_dlc_size_all_file_en.text(),
                                                        self.le_base_size_last_file_en.text(),self.le_update_size_last_file_en.text(),self.le_dlc_size_last_file_en.text()]})
        dict_links = dict_en_server_link.copy()

        dict_output = {}
        for i in range(len(list_server)):
                c1=str(i)
                list_links_base = txt_links_en_maker(dict_links[c1][0])
                list_links_update = txt_links_en_maker(dict_links[c1][1])
                list_links_dlc = txt_links_en_maker(dict_links[c1][2])
                if list_links_base != [0,'']:
                        base = self.insert_size_in_link_list([list_links_base[1]],
                                                        dict_links[c1][3],
                                                        dict_links[c1][6],
                                                        list_links_base[0],
                                                        self.le_base_version.text(),
                                                        self.le_base_format.text(),
                                                        self.le_base_title_id.text())
                else:
                        base = ''
                if list_links_update != [0,'']:
                        update = self.insert_size_in_link_list([list_links_update[1]],
                                                        dict_links[c1][4],
                                                        dict_links[c1][7],
                                                        list_links_update[0],
                                                        self.le_update_version.text(),
                                                        self.le_update_format.text(),
                                                        self.le_update_title_id.text())
                else:
                        update = ''
                if list_links_dlc != [0,'']:
                        dlc = self.insert_size_in_link_list([list_links_dlc[1]],
                                                        dict_links[c1][5],
                                                        dict_links[c1][8],
                                                        list_links_dlc[0],
                                                        self.le_dlc_version.text(),
                                                        'NSP',
                                                        self.le_dlc_title_id.text())
                else:
                        dlc = ''
                dict_output.update({c1:[base,update,dlc]})
        copy(str(dict_output))
if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        app.setWindowIcon(QtGui.QIcon(os.path.join(basedir1()+'/icon.ico')))
        link_maker = QtWidgets.QMainWindow()
        ui = Ui_link_maker()
        ui.setupUi(link_maker)
        link_maker.show()
        sys.exit(app.exec())
